# Making the map readable by agents that are not Claude Code: MCP for the ones
# that speak it, generated context files for the ones that read markdown.

MARK_START='<!-- orgami:start — generated, edit above or below this block -->'
MARK_END='<!-- orgami:end -->'

# The block that gets written into a repo's own context file.
agents_block() {
  local repo=$1
  echo "$MARK_START"
  echo
  "$ORGAMI_BIN" brief "$repo" 2>/dev/null | sed 's/^team notes on this repo:/Team notes on this repo:/'
  cat <<'TAIL'

The full page, the organization map, recorded decisions and the team's notes are
available from the `orgami` CLI:

    orgami context          this repo, in full
    orgami context --org    the organization
    orgami notes            what the team has hit before
    orgami note "..."       record something durable (ask first — it is shared)

Prefer these over re-deriving the same facts. Every claim in the map carries the
file:line, URL or pull request it came from; cite it. A missing link means "not
found in committed configuration", never "not connected".
TAIL
  echo
  echo "$MARK_END"
}

# Replaces the managed block in place, leaving everything else alone.
agents_splice() {
  local file=$1 block=$2
  if [[ -f $file ]] && grep -qF "$MARK_START" "$file"; then
    local tmp
    tmp=$(mktemp)
    awk -v start="$MARK_START" -v end="$MARK_END" -v blockfile="$block" '
      index($0, start) { system("cat " blockfile); skip = 1; next }
      index($0, end) { skip = 0; next }
      !skip { print }
    ' "$file" >"$tmp"
    mv "$tmp" "$file"
  else
    [[ -f $file ]] && printf '\n' >>"$file"
    cat "$block" >>"$file"
  fi
}

cmd_agents() {
  source "$ROOT/lib/card.sh"
  local targets=() repo="" dir=$PWD action=write workspace="" scope=project

  while [[ $# -gt 0 ]]; do
    case $1 in
      --agents-md) targets+=(agents) ; shift ;;
      --cursor) targets+=(cursor); shift ;;
      --all) targets=(agents cursor); shift ;;
      --repo) repo=$2; shift 2 ;;
      --refresh) action=refresh; shift ;;
      --workspace) workspace=$2; shift 2 ;;
      --cursor-hook) action=cursor-hook; shift ;;
      --user) scope=user; shift ;;
      --git-hook) action=git-hook; shift ;;
      *) die "unknown flag: $1" ;;
    esac
  done

  case $action in
    refresh) agents_refresh "$workspace"; return ;;
    cursor-hook) agents_cursor_hook "$scope"; return ;;
    git-hook) agents_git_hook; return ;;
  esac

  context_pick_company
  load_company
  [[ -f $DIR/map/repos.json ]] || die "no map yet — run: orgami scan"

  [[ -n $repo ]] || repo=$(card_repo_here 2>/dev/null || true)
  jq -e --arg r "$repo" 'any(.[]; .name == $r)' "$DIR/map/repos.json" >/dev/null 2>&1 ||
    die "'$repo' is not in the $COMPANY map — run this inside a mapped checkout, or pass --repo"

  [[ ${#targets[@]} -gt 0 ]] || {
    targets=(agents)
    [[ -d $dir/.cursor ]] && targets+=(cursor)
  }

  local block
  block=$(mktemp)
  agents_block "$repo" >"$block"

  local t
  for t in "${targets[@]}"; do
    case $t in
      agents)
        agents_splice "$dir/AGENTS.md" "$block"
        echo "$dir/AGENTS.md"
        ;;
      cursor)
        mkdir -p "$dir/.cursor/rules"
        local mdc="$dir/.cursor/rules/orgami.mdc"
        {
          echo "---"
          echo "description: Organization context for $repo, generated by orgami"
          echo "alwaysApply: true"
          echo "---"
          echo
          cat "$block"
        } >"$mdc"
        echo "$mdc"
        ;;
    esac
  done
  rm -f "$block"

  echo
  log "these files live in the repository — commit them only if the team wants them there"
  log "re-run 'orgami agents' after a scan to refresh the block"
}

# ------------------------------------------------------------------ MCP wiring

# Prefer the bare name: it is on PATH after install.sh, and an absolute path
# with a space in it breaks half the clients' config parsers.
mcp_bin() { command -v orgami 2>/dev/null || echo "${ORGAMI_BIN:-orgami}"; }

mcp_config_json() {
  jq -n --arg bin "$(mcp_bin)" \
    '{mcpServers: {orgami: {command: $bin, args: ["mcp"]}}}'
}

cmd_mcp_config() {
  local client=${1:-}
  case $client in
    cursor | windsurf | claude-desktop | zed | vscode)
      mcp_config_json
      ;;
    opencode)
      jq -n --arg bin "$(mcp_bin)" \
        '{"$schema": "https://opencode.ai/config.json",
          mcp: {orgami: {type: "local", command: [$bin, "mcp"], enabled: true}}}'
      ;;
    codex)
      cat <<EOF
[mcp_servers.orgami]
command = "$(mcp_bin)"
args = ["mcp"]
EOF
      ;;
    claude-code)
      echo "claude mcp add orgami -- $(mcp_bin) mcp"
      ;;
    *)
      cat >&2 <<'EOF'
usage: orgami mcp --config <client>

  cursor          merge into ~/.cursor/mcp.json, or .cursor/mcp.json in a project
  opencode        merge into ~/.config/opencode/opencode.json, or ./opencode.json
  codex           append to ~/.codex/config.toml
  claude-code     a command to run
  windsurf        merge into ~/.codeium/windsurf/mcp_config.json
  zed             merge into the "context_servers" block of Zed's settings
  vscode          merge into .vscode/mcp.json
  claude-desktop  merge into the Claude Desktop config
EOF
      return 1
      ;;
  esac
}

# ------------------------------------------------------- keeping blocks fresh

# Every checkout under the company's workspace roots that already carries an
# orgami block gets it rewritten. Nothing new is created here.
agents_refresh() {
  local extra=${1:-}
  context_pick_company
  load_company
  [[ -f $DIR/map/repos.json ]] || die "no map yet — run: orgami scan"

  local roots=()
  mapfile -t roots < <(jq -r '(.workspaces // [])[]' "$DIR/config.json" 2>/dev/null)
  [[ -n $extra ]] && roots+=("$extra")
  [[ ${#roots[@]} -gt 0 ]] || die "no workspace configured — orgami agents --refresh --workspace ~/Work/<client>"

  # Remember a workspace passed on the command line, so the next run is bare.
  if [[ -n $extra ]]; then
    local tmp
    tmp=$(mktemp)
    jq --arg w "$extra" '.workspaces = ((.workspaces // []) + [$w] | unique)' \
      "$DIR/config.json" >"$tmp"
    mv "$tmp" "$DIR/config.json"
  fi

  local root checkout repo block n=0
  block=$(mktemp)
  for root in "${roots[@]}"; do
    root=${root/#\~/$HOME}
    [[ -d $root ]] || continue
    while read -r checkout; do
      [[ -n $checkout ]] || continue
      repo=$(card_repo_here "$checkout") || continue
      jq -e --arg r "$repo" 'any(.[]; .name == $r)' "$DIR/map/repos.json" >/dev/null 2>&1 || continue

      local touched=0
      if [[ -f $checkout/AGENTS.md ]] && grep -qF "$MARK_START" "$checkout/AGENTS.md"; then
        agents_block "$repo" >"$block"
        agents_splice "$checkout/AGENTS.md" "$block"
        touched=1
      fi
      if [[ -f $checkout/.cursor/rules/orgami.mdc ]]; then
        agents_block "$repo" >"$block"
        {
          echo "---"
          echo "description: Organization context for $repo, generated by orgami"
          echo "alwaysApply: true"
          echo "---"
          echo
          cat "$block"
        } >"$checkout/.cursor/rules/orgami.mdc"
        touched=1
      fi
      [[ $touched == 1 ]] && { n=$((n + 1)); echo "  refreshed $repo"; }
    done < <(find_dirs_containing "$root" .git 5)
  done
  rm -f "$block"
  echo "$n checkout(s) refreshed"
}

# Cursor fires sessionStart and takes {"additional_context": "..."} on stdout.
agents_cursor_hook() {
  local scope=${1:-project}
  local target
  if [[ $scope == user ]]; then
    target="$HOME/.cursor/hooks.json"
  else
    target="$PWD/.cursor/hooks.json"
  fi
  mkdir -p "$(dirname "$target")"
  [[ -f $target ]] || echo '{"version": 1, "hooks": {}}' >"$target"

  local script="$ROOT/hooks/session-context.sh"
  local tmp
  tmp=$(mktemp)
  jq --arg cmd "bash \"$script\" --json" \
    '.version = (.version // 1)
     | .hooks = (.hooks // {})
     | .hooks.sessionStart = (((.hooks.sessionStart // [])
         | map(select((.command // "") | contains("session-context.sh") | not)))
         + [{command: $cmd, type: "command", timeout: 15}])' \
    "$target" >"$tmp"
  mv "$tmp" "$target"
  echo "$target"
  log "Cursor will now inject this repo's orgami context at the start of every session"
}

# Refresh the block whenever the working tree changes underneath it.
agents_git_hook() {
  local top
  top=$(git rev-parse --show-toplevel 2>/dev/null) || die "not inside a git checkout"
  local h
  for h in post-merge post-checkout post-rewrite; do
    local file="$top/.git/hooks/$h"
    if [[ -f $file ]] && ! grep -q 'orgami agents' "$file"; then
      printf '\n# orgami: keep the generated context block current\ncommand -v orgami >/dev/null && orgami agents >/dev/null 2>&1 || true\n' >>"$file"
    elif [[ ! -f $file ]]; then
      printf '#!/bin/sh\n# orgami: keep the generated context block current\ncommand -v orgami >/dev/null && orgami agents >/dev/null 2>&1 || true\n' >"$file"
      chmod +x "$file"
    fi
    echo "$file"
  done
}
