# shellcheck shell=bash
# orgami publish — commit the reports and the map into the configured docs repo.

ORGAMI_MARK="<!-- generated by orgami -->"

# The page GitHub shows when the repo is opened: the latest recap first, then
# everything else. Written to our own directory always, and to the repository
# root only when nobody else owns that README.
publish_front_page() {
  local dest=$1 work=$2 path=$3
  local latest week
  latest=$(find "$DIR/reports" -maxdepth 1 -name '*.md' 2>/dev/null | sort | tail -1)
  [[ -n $latest ]] || return 0
  week=$(basename "$latest" .md)

  local page
  page=$(mktemp)
  {
    echo "$ORGAMI_MARK"
    echo "# $COMPANY engineering"
    echo
    echo "Weekly recaps of every merged pull request, a map of how the repositories"
    echo "fit together, and the runbooks for operating them. Generated by"
    echo "[orgami](https://github.com/achevalier-dev/orgami) from \`$ORG\`."
    echo
    local project
    project=$(cfg claude_project)
    if [[ -n $project ]]; then
      echo "### [→ Ask Claude about any of this]($project)"
      echo
      echo "<sub>Answers come from the files in this repository, with the change that"
      echo "backs each claim. First visit asks you to sign in.</sub>"
      echo
    elif [[ -f $DIR/map/ASK-CLAUDE.md ]]; then
      echo "**[Ask questions about this instead of reading it]($path/ASK-CLAUDE.md)** —"
      echo "a few minutes to set up, nothing to install."
      echo
    fi

    echo "## This week — [$week]($path/reports/$week.md)"
    echo
    sed -n '3p' "$latest"
    echo
    sed -n '/^## Summary/,/^## /p' "$latest" | sed '1d;$d' | sed '/^$/d'
    echo
    local urgent
    urgent=$(sed -n '/^## Action required/,/^## /p' "$latest" | grep -c '^- ' || true)
    [[ ${urgent:-0} -gt 0 ]] &&
      echo "**$urgent things need someone to act on them** — see [Action required]($path/reports/$week.md#action-required)."
    echo
    echo "[Read the full recap →]($path/reports/$week.md)"
    echo
    if [[ -f $DIR/map/ASK-CLAUDE.md ]]; then
      echo "Rather ask than read? [**Ask Claude about any of this**]($path/ASK-CLAUDE.md)"
      echo "sets it up in a few minutes, no installing anything."
      echo
    fi

    echo "## Everything else"
    echo
    echo "| | |"
    echo "|---|---|"
    [[ -f $DIR/map/ARCHITECTURE.md ]] &&
      echo "| [Architecture]($path/ARCHITECTURE.md) | how the repositories connect, what deploys them, which hosts they reach |"
    [[ -f $DIR/map/RUNBOOK.md ]] &&
      echo "| [Runbook]($path/RUNBOOK.md) | how everything ships, shared services, health endpoints |"
    [[ -f $DIR/map/PLAYBOOKS.md ]] &&
      echo "| [Playbooks]($path/PLAYBOOKS.md) | how a kind of change that keeps coming round is made here |"
    [[ -f $DIR/map/INCIDENTS.md ]] &&
      echo "| [Incidents]($path/INCIDENTS.md) | what pages you, what has broken before and what it turned out to be |"
    [[ -f $DIR/map/DECISIONS.md ]] &&
      echo "| [Decisions]($path/DECISIONS.md) | why things are the way they are, with the pull request for each |"
    [[ -f $DIR/map/ADVISE.md ]] &&
      echo "| [Vendors]($path/ADVISE.md) | every third-party service the code names, and what looks worth consolidating |"
    [[ -f $DIR/map/DNS.md ]] &&
      echo "| [DNS]($path/DNS.md) | the vendors the organization's public DNS says it has an account with |"
    [[ -f $DIR/map/CONVENTIONS.md ]] &&
      echo "| [Conventions]($path/CONVENTIONS.md) | every AGENTS.md and CLAUDE.md committed in the org |"
    echo "| [All recaps]($path/reports/) | week by week |"
    echo "| [Per-repo pages]($path/repos/) | one page per repository |"
    echo
    echo "<sub>Regenerated automatically. Edits here are overwritten — record"
    echo "anything worth keeping with \`orgami note\`.</sub>"
  } >"$page"

  # Inside our own directory the paths are relative to it, not to the root.
  sed "s|]($path/|](|g" "$page" >"$dest/README.md"

  # Claim the repository's README only when nobody else has written one: it is
  # missing, it is already ours, or it is still the stub GitHub creates.
  local root="$work/README.md"
  if [[ ! -f $root ]] || grep -qF "$ORGAMI_MARK" "$root" ||
    [[ $(grep -c . "$root") -le 5 ]]; then
    cp "$page" "$root"
  fi
  rm -f "$page"
}

# One line per week, newest first.
publish_report_index() {
  local dest=$1 f week day
  {
    echo "$ORGAMI_MARK"
    echo "# Weekly recaps"
    echo
    while IFS= read -r f; do
      week=$(basename "$f" .md)
      echo "- [**$week**]($week.md) — $(sed -n '3p' "$f")"
    done < <(find "$DIR/reports" -maxdepth 1 -name '*.md' 2>/dev/null | sort -r)

    # The last fortnight of daily digests. Older ones stay in the directory and
    # in git; an index nobody scrolls is not an index.
    if compgen -G "$DIR/reports/daily/*.md" >/dev/null; then
      echo
      echo "# Daily"
      echo
      while IFS= read -r f; do
        day=$(basename "$f" .md)
        echo "- [$day](daily/$day.md) — $(sed -n '/^[0-9]/p' "$f" | tail -1)"
      done < <(find "$DIR/reports/daily" -maxdepth 1 -name '*.md' 2>/dev/null | sort -r | head -14)
    fi
  } >"$dest/reports/README.md"
}

cmd_publish() {
  load_company
  need git

  local yes=0 dry=0
  while [[ $# -gt 0 ]]; do
    case $1 in
      --yes|-y) yes=1; shift ;;
      --dry-run) dry=1; shift ;;
      *) die "unknown flag: $1" ;;
    esac
  done

  local repo path
  repo=$(cfg docs_repo)
  path=$(cfg docs_path orgami)
  [[ -n $repo ]] || die "no docs_repo in $DIR/config.json — set it, or read the files in $DIR"

  local work="$DIR/cache/docs"
  if [[ -d $work/.git ]]; then
    git -C "$work" fetch --quiet origin
  else
    git clone --quiet --depth 1 "$repo" "$work" || die "cannot clone $repo"
  fi

  # Notes sync leaves this checkout on its own branch. Get back onto the default
  # one before writing anything, or the whole map lands on someone's note PR.
  local main
  # `|| true` matters: with set -e, an assignment whose command substitution
  # fails ends the script here, which is why an empty docs repo used to make
  # publish exit without a word.
  main=$(git -C "$work" rev-parse --abbrev-ref origin/HEAD 2>/dev/null | sed 's|origin/||' || true)
  # An empty remote has no origin/HEAD, and rev-parse answers with the literal
  # "HEAD" — which is not a branch anyone can check out.
  [[ -n $main && $main != HEAD ]] ||
    main=$(git -C "$work" symbolic-ref --short HEAD 2>/dev/null || echo main)
  [[ -n $main && $main != HEAD ]] || main=main
  # A docs repo someone just created has no commits, so there is no
  # origin/<main> to start from — begin the branch here instead of refusing.
  if git -C "$work" rev-parse --verify --quiet "origin/$main" >/dev/null; then
    git -C "$work" checkout -B "$main" --quiet "origin/$main" ||
      die "cannot get onto $main in the docs repo"
  else
    git -C "$work" checkout -B "$main" --quiet ||
      die "cannot start $main in the docs repo"
    log "$repo is empty — this publish will be its first commit"
  fi

  local dest="$work/$path"
  mkdir -p "$dest/reports"
  cp -f "$DIR/reports/"*.md "$dest/reports/" 2>/dev/null || true
  if compgen -G "$DIR/reports/daily/*.md" >/dev/null; then
    mkdir -p "$dest/reports/daily"
    cp -f "$DIR/reports/daily/"*.md "$dest/reports/daily/" 2>/dev/null || true
  fi
  local f
  # dns.json and DNS.md publish like the rest of the map, unlike live.json
  # below. The difference is not a policy choice: a DNS record is public, so
  # anyone holding the page can run the same `dig` and check it. That makes the
  # reading reproducible, which is the property everything else in this list has
  # and a cloud reading does not.
  for f in ARCHITECTURE.md CONVENTIONS.md DECISIONS.md RUNBOOK.md PLAYBOOKS.md INCIDENTS.md ASK-CLAUDE.md ADVISE.md DNS.md graph.json graph.html repos.json coupling.json advise.json dns.json; do
    cp -f "$DIR/map/$f" "$dest/" 2>/dev/null || true
  done

  # depth.json stays on the machine that parsed. It is the symbol index for
  # forty repositories — ninety thousand lines against graph.json's two
  # thousand — and a docs repo people read the weekly diff of is the wrong home
  # for a file that size. `orgami depth --symbol` and the MCP tool read it
  # locally, which is where the question gets asked anyway.

  # The live reading is a snapshot of one person's view of a cloud account, and
  # it goes stale in the repo where the rest of the map does not. It reaches the
  # docs repo only when the org has said it should.
  if [[ $(cfg live_publish false) == true ]]; then
    cp -f "$DIR/map/live.json" "$dest/" 2>/dev/null || true
  fi
  if compgen -G "$DIR/map/repos/*.md" >/dev/null; then
    mkdir -p "$dest/repos"
    cp -f "$DIR/map/repos/"*.md "$dest/repos/" 2>/dev/null || true
  fi
  if compgen -G "$DIR/map/runbooks/*.md" >/dev/null; then
    mkdir -p "$dest/runbooks"
    cp -f "$DIR/map/runbooks/"*.md "$dest/runbooks/" 2>/dev/null || true
  fi
  if compgen -G "$DIR/map/playbooks/*.md" >/dev/null; then
    mkdir -p "$dest/playbooks"
    cp -f "$DIR/map/playbooks/"*.md "$dest/playbooks/" 2>/dev/null || true
  fi

  # How this company wants notes handled, so a teammate who joins inherits it
  # instead of each machine deciding for itself.
  jq '{notes_autopublish: (.notes_autopublish // false),
       notes_review: (.notes_review // false),
       notes_auto_merge: (.notes_auto_merge // false),
       report_model: (.report_model // "claude-sonnet-5")}' \
    "$DIR/config.json" >"$dest/settings.json" 2>/dev/null || true

  publish_front_page "$dest" "$work" "$path"
  publish_report_index "$dest"

  if [[ -z $(git -C "$work" status --porcelain) ]]; then
    echo "nothing to publish — docs repo already matches"
    return
  fi

  # docs_path can be empty, meaning the map is the repository rather than a
  # directory inside one. git add wants a pathspec, and "" is not one.
  git -C "$work" add -A "${path:-.}"
  [[ -f $work/README.md ]] && git -C "$work" add README.md
  echo "changes to publish in $repo:$path"
  git -C "$work" --no-pager diff --cached --stat

  [[ $dry == 1 ]] && { git -C "$work" reset --quiet; return; }

  if [[ $yes == 0 ]]; then
    read -rp "push to $repo? [y/N] " ans
    [[ $(printf '%s' "$ans" | tr '[:upper:]' '[:lower:]') == y* ]] || { git -C "$work" reset --quiet; die "aborted"; }
  fi

  local msg
  msg="docs(orgami): $COMPANY $(iso_week) recap and map"
  git -C "$work" commit --quiet -m "$msg"
  git -C "$work" push --quiet origin HEAD
  echo "pushed: $msg"
}

# orgami weekly — the whole loop, for the systemd timer.
cmd_weekly() {
  load_company
  # The timer is the one moment a week nobody is waiting on the terminal, which
  # makes it the right place to take the newest orgami before running the rest.
  # It refuses a checkout with work in it, so a machine that develops orgami is
  # never pulled from underneath.
  source "$ROOT/lib/update.sh"
  cmd_update --quiet || true
  cmd_pull --last 0
  cmd_report
  cmd_scan
  cmd_coupling
  # Refresh a live reading that already exists. Nobody's first run of the timer
  # starts talking to cloud accounts on its own.
  if [[ -f $DIR/map/live.json ]]; then
    source "$ROOT/lib/live.sh"
    cmd_live --quiet >/dev/null || true
  fi
  # Same rule for the DNS reading: refresh one that exists, never start one. A
  # timer that begins querying somebody's domains because it was installed is
  # not a timer anyone asked for.
  if [[ -f $DIR/map/dns.json ]]; then
    source "$ROOT/lib/dns.sh"
    cmd_dns --yes >/dev/null || true
  fi
  cmd_doc
  if [[ $(jq -r '(.workspaces // []) | length' "$DIR/config.json") -gt 0 ]]; then
    source "$ROOT/lib/agents.sh"
    cmd_agents --refresh || true
  fi
  if [[ -n $(cfg docs_repo) ]]; then
    cmd_sync || true
    # Read whatever is waiting for review, so notes do not sit for a week.
    if [[ $(cfg notes_review false) == true ]]; then
      source "$ROOT/lib/notes.sh"
      cmd_review --auto || true
    fi
    cmd_publish --yes
  else
    log "no docs_repo configured — report left in $DIR/reports"
  fi
}
