# orgami report — deterministic stats by jq, narrative by claude.
# Numbers never come from the model.

cmd_report() {
  load_company
  need jq
  need claude "the report narrative is written by Claude Code in headless mode"

  local week="" model=""
  while [[ $# -gt 0 ]]; do
    case $1 in
      --week) week=$2; shift 2 ;;
      --model) model=$2; shift 2 ;;
      --stats-only) STATS_ONLY=1; shift ;;
      *) die "unknown flag: $1" ;;
    esac
  done

  [[ -n $week ]] || week=$(iso_week)
  local src="$DIR/cache/prs/$week.json"
  [[ -f $src ]] || die "no cache for $week — run: orgami pull"

  local count
  count=$(jq '.prs | length' "$src")
  [[ $count -gt 0 ]] || die "no merged PRs in $week"

  local stats="$DIR/cache/prs/$week.stats.json"
  jq -f "$ROOT/lib/stats.jq" "$src" >"$stats"

  if [[ ${STATS_ONLY:-0} == 1 ]]; then
    cat "$stats"
    return
  fi

  # Trim bodies and comments hard — the model needs intent, not diffs.
  local digest
  digest=$(mktemp)
  jq '[.prs[] | {
        repo: .repository.name,
        number, title, url,
        author: (.author.login // "unknown"),
        body: (.bodyText // "" | .[0:600]),
        labels: [.labels.nodes[].name],
        additions, deletions, changedFiles,
        merged: .mergedAt,
        reviewers: [.reviews.nodes[] | select(.state == "APPROVED"
                    or .state == "CHANGES_REQUESTED")
                    | {(.author.login // "unknown"): .state}] | add,
        review_notes: [.reviewThreads.nodes[].comments.nodes[]
                       | {path, note: (.bodyText // "" | .[0:200])}] | .[0:5]
      }]' "$src" >"$digest"

  [[ -n $model ]] || model=$(cfg report_model claude-sonnet-5)
  local out="$DIR/reports/$week.md"

  log "writing $week recap over $count PRs with $model"

  {
    cat "$ROOT/prompts/recap.md"
    printf '\n\nSTATS\n```json\n'
    cat "$stats"
    printf '\n```\n\nPULL_REQUESTS\n```json\n'
    cat "$digest"
    printf '\n```\n'
  } | claude -p --model "$model" --output-format text >"$out.body" ||
    die "claude failed — is 'claude' authenticated?"

  rm -f "$digest"

  {
    echo "# $COMPANY — week $week"
    echo
    echo "\`$(jq -r .since "$stats")\` to \`$(jq -r .until "$stats")\` · \
$(jq -r .merged "$stats") merged PRs · \
$(jq -r .repos_touched "$stats") repos · \
median $(jq -r .median_hours_to_merge "$stats")h to merge"
    echo
    cat "$out.body"
    echo
    echo "---"
    echo
    echo "<sub>Generated by [orgami](https://github.com/achevalier-dev/orgami) on \
$(date -u +%Y-%m-%d). Numbers computed from the GitHub API; prose written by \`$model\`.</sub>"
  } >"$out"
  rm -f "$out.body"

  echo "$out"
}
